### PR TITLE
Fix #1767 - NPE on OptionSpec.getValue() (IScoped)

### LINKED ISSUE #1767: NPE on OptionSpec.getValue()
For options defined in an ArgGroup, a call to OptionSpec.getValue() will fail due to a NullPointerException if none of the options contained in the ArgGroup have been specified on the command line.

The following command class demonstrates this issue:
```java
@Command(name = "testGetValue")
public class TestGetValueCommand implements Runnable {
	@Spec CommandSpec spec;
	@Option(names="--arg1") private String arg1;
	@ArgGroup private MyArgGroup argGroup;
	
	private static final class MyArgGroup {
		@Option(names="--arg2") private String arg2;
		@Option(names="--arg3") private String arg3;
	}
	
	@Override
	public void run() {
		spec.options().stream().map(OptionSpec::getValue).forEach(this::printOptionValue);
	}
	
	private void printOptionValue(Object value) {
		System.out.println("Option value: "+value);
	}
}
```

This command will fail with an exception on `OptionSpec::getValue` if neither `--arg2` nor `--arg3` have been specified on the command line.

A simple null-check in the `FieldBinding#get()` method fixes this issue; we will be submitting a PR for this:
```java
@SuppressWarnings("unchecked") T result = obj==null ? null : (T) field.get(obj);
```

Note that the `FieldBinding#set()` method likely exhibits the same problem, however this may be more difficult to fix; if an ArgGroup is null, then there's no object to set the option value on. As such, we won't be including any fix for the `set()` method in the PR. 

It might make sense to always initialize ArgGroups with a non-null value, as that would avoid these kind of issues, and would also reduce the number of null checks in command implementations when trying to access options defined in an ArgGroup. Not sure though whether there are any command implementations that rely on the fact that an ArgGroup is null if none of the options in that ArgGroup have been specified on the command line, so this would potentially be a breaking change.

### PR DESCRIPTION
**Pull request by rsenden**
This PR fixes https://github.com/remkop/picocli/issues/1767, based on the IScoped approach discussed in the issue

### CODE REVIEW

File: src/main/java/picocli/CommandLine.java [hunk 1]
```diff
@@ -5995,6 +5995,15 @@ private Model() {}
          * @since 4.0
          */
         public interface IScope extends IGetter, ISetter {}
+        
+        /** This interface provides access to an {@link IScope} instance. 
+         */
```
Comment (remkop) [inline src/main/java/picocli/CommandLine.java:6000]: Can we add a  `@since` tag to the javadoc for this new interface?

```
@since 4.7
```

File: src/main/java/picocli/CommandLine.java [hunk 2]
```diff
@@ -9166,9 +9175,25 @@ private String defaultValueFromProvider() {
              * @return whether this argument applies to all descendent subcommands of the command where it is defined
              * @since 4.3 */
             public ScopeType scopeType() { return scopeType; }
+            
+            /** Check whether the {@link #getValue()} method is able to get an actual value from the current {@link #getter()}. */
```
Comment (remkop) [inline src/main/java/picocli/CommandLine.java:9179]: Can we add a `@since` tag to the javadoc for this new public method?

```
@since 4.7
```

File: src/main/java/picocli/CommandLine.java [hunk 3]
```diff
@@ -9166,9 +9175,25 @@ private String defaultValueFromProvider() {
...
+            public boolean isValueGettable() {
+                if (getter instanceof IScoped) {
+                    IScoped scoped = (IScoped) getter;
+                    IScope scope = scoped.getScope();
+                    try {
+                        Object obj = scope.get();
+                        return obj != null;
```
Comment (remkop) [inline src/main/java/picocli/CommandLine.java:9186]: The `IScope scope` object itself (what is returned from `scoped.getScope()`) may also be `null`.
We have a try/catch around this, so any NPEs would be caught and handled correctly, but should we do this instead?

```java
return scope != null && scope.get() != null;
```

**Review by remkop — CHANGES_REQUESTED** [review]
Thank you for this PR!
I do prefer this approach to the IGetterAccessChecker alternative approach in https://github.com/remkop/picocli/pull/1801

I have some requests for minor changes, can you take a look?

File: src/main/java/picocli/CommandLine.java (hunk 3 above)
Comment (rsenden) [reply src/main/java/picocli/CommandLine.java:9186]: Implemented all changes as requested

**Review by remkop — APPROVED** [review]

**Comment by remkop** [comment]
Merged. Thank you for the PR!
