### PR TITLE
[issue 1387] Validate final primitive|String fields w/ Option|Parameters annotations

### LINKED ISSUE #1387: Annotation processor should validate final primitive and String fields (was: Annotation processor not working)
## Source
```java
@Option(names = {"-h", "--host"})
private final String hostname = "localhost"; // <-- notice the final
```

## pom.xml
```xml
<build>
    <pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <!-- annotationProcessorPaths requires maven-compiler-plugin version 3.5 or higher -->
                <version>3.8.1</version>
                <configuration>
                  <annotationProcessorPaths>
                    <path>
                      <groupId>info.picocli</groupId>
                      <artifactId>picocli-codegen</artifactId>
                      <version>4.6.1</version>
                    </path>
                  </annotationProcessorPaths>
                  <compilerArgs>
                    <arg>-Aproject=${project.groupId}/${project.artifactId}</arg>
                  </compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </pluginManagement>
</build>
```

## mvn compile
```
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------------------< ... >---------------------------------
[INFO] Building ... 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ... ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory ...\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ ... ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to ...\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.627 s
[INFO] Finished at: 2021-07-09T22:10:22+02:00
[INFO] ------------------------------------------------------------------------
```

## Running
```
Exception in thread "main" picocli.CommandLine$InitializationException: Constant (final) primitive and String fields like private final java.lang.String ....hostname cannot be used as an @Option: compile-time constant inlining may hide new values written to it.
	at picocli.CommandLine$Model$CommandReflection.validateArgSpecMember(CommandLine.java:11571)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedTypedMembers(CommandLine.java:11516)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedFields(CommandLine.java:11466)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11399)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6202)
	at picocli.CommandLine.<init>(CommandLine.java:227)
	at picocli.CommandLine.<init>(CommandLine.java:221)
	at picocli.CommandLine.<init>(CommandLine.java:196)
	at ....main(....java:44)
```

### PR DESCRIPTION
**Pull request by acmcelwee**
Fixes #1387

### CODE REVIEW

File: picocli-codegen/src/main/java/picocli/codegen/annotation/processing/AnnotationValidator.java [hunk 1]
```diff
@@ -196,16 +208,33 @@ private void validateInvalidCombinations(RoundEnvironment roundEnv) {
...
+        // We have an existing validator for fields in an interface. Ignore those elements here.
+        boolean shouldValidateFinal = elementKind.isField() && !isInterfaceField(e);
+        if (!isFinal || !shouldValidateFinal) {
+            return;
+        }
+        boolean isConstantValueField = false;
+        for (VariableElement variableElement : ElementFilter.fieldsIn(Collections.singletonList(e))) {
+             isConstantValueField = isConstantValueField || variableElement.getConstantValue() != null;
+        }
+        if ((type.getKind().isPrimitive() || typeUtils.isAssignable(type, stringType)) && isConstantValueField) {
```
Comment (acmcelwee) [inline picocli-codegen/src/main/java/picocli/codegen/annotation/processing/AnnotationValidator.java:233]: While I'd love to also apply this compile-time validation to the boxed primitive types, I don't know if there's actually a way to determine if `final Integer foo` has a value specified in the class definition. `getConstantValue()` only returns a non-null value if the defined value is non-null **and** the type is a true primitive type or string.

File: picocli-annotation-processing-tests/src/test/java/picocli/annotation/processing/tests/AbstractCommandSpecProcessorTest.java [hunk 2]
```diff
@@ -225,9 +226,49 @@ public void testInvalidSplitOnSinglValueOptionOrPositional() {
...
+        String errorFormat = "Constant (final) primitive and String fields like %s cannot be used as %s: compile-time constant inlining may hide new values written to it.";
+        List<String> expectedValidationErrors = new ArrayList<String>();
+        for (String type : types) {
+            String titleized = type.substring(0, 1).toUpperCase() + type.substring(1);
+            String invalidOptionField = String.format("invalid%s", titleized);
+            String invalidParamField = String.format("invalid%sParam", titleized);
+
+            expectedValidationErrors.add(String.format(errorFormat, invalidOptionField, "@Option"));
+            expectedValidationErrors.add(String.format(errorFormat, invalidParamField, "@Parameters"));
+        }
```
Comment (acmcelwee) [inline picocli-annotation-processing-tests/src/test/java/picocli/annotation/processing/tests/AbstractCommandSpecProcessorTest.java:263]: Oh, I also wasn't certain about the java version where these tests get executed, but I demonstrated considerable restraint and wrote this test to only use java 6+ language features.

**Comment by remkop** [comment]
Thank you for the contribution!
I wanted to reply quickly to say thank you, but I won’t be able to review in detail until after this weekend.

**Comment by acmcelwee** [comment]
No worries! I don't currently need this functionality, but I used this open issue as a prompt for a programming exercise with a candidate I interviewed today. Before I asked someone to try it, I took the time to work through the problem, and I figured the best use of that effort was to contribute back to a tool we use at work.

**Comment by remkop** [comment]
I mis-clicked and accidentally merged before reviewing. 😅
I won’t be able to review it for a few more days; I hope you’re okay with the delayed feedback. (But I’m sure it’ll be solid stuff anyway.) 😄
Thanks again 🙏

**Comment by remkop** [comment]
Please ignore my previous comment; that comment was intended for a different PR: #1708.  😅

**Comment by remkop** [comment]
Merged. Thank you for the contribution!
